import Link from "next/link";
import { Icon } from "../layout/icon";

export function SectionPlaceholder({ title, description, primaryAction }: { title: string; description: string; primaryAction: string }) {
  return <>
    <section className="hero-card"><div className="hero-label">MVP foundation</div><div className="hero-value" style={{ fontSize: "clamp(28px, 4vw, 44px)", maxWidth: 620 }}>{title}</div><p className="page-description" style={{ marginTop: 0 }}>{description}</p><div className="hero-note"><span className="status-dot" /><span><strong>No financial data is mocked.</strong> This surface will be connected to normalized market data and your Supabase records.</span></div></section>
    <div className="placeholder-grid"><section className="panel placeholder-card"><div className="panel-title">Data source</div><div className="panel-caption">Provider status and freshness</div><div className="placeholder-table"><div className="placeholder-row" /><div className="placeholder-row short" /><div className="placeholder-row" /></div></section><section className="panel placeholder-card"><div className="panel-title">Your data</div><div className="panel-caption">Private records and preferences</div><div className="placeholder-table"><div className="placeholder-row short" /><div className="placeholder-row" /><div className="placeholder-row short" /></div></section><section className="panel placeholder-card"><div className="panel-title">Assistant context</div><div className="panel-caption">Sources, assumptions and uncertainty</div><div className="placeholder-table"><div className="placeholder-row" /><div className="placeholder-row short" /><div className="placeholder-row" /></div></section></div>
    <section className="panel" style={{ marginTop: 16 }}><div className="panel-header"><div><div className="panel-title">Ready for the next step</div><div className="panel-caption">The architecture is documented before any provider is connected.</div></div><Link className="button button-primary" href="/settings">{primaryAction}<Icon name="arrow" size={14} /></Link></div><div className="insight-row"><span className="insight-marker" /><div className="insight-text">This screen is intentionally honest about its data state. It will never replace missing prices with made-up numbers or hide a stale timestamp.</div></div></section>
  </>;
}
